### ISSUE TITLE
How to verify account ownership?

### ISSUE THREAD

**Issue by ismyhc** [worldwide-asset-exchange/waxjs#102]
Is there a way to verify a users ownership of wax account via WaxJS? I need to be able to verify from the backend. Having the client pass to me simply an account name is not sufficient. 

I can do this with anchor via their IdentityProof after initiating a login, or with eosjs by asking the user to sign an arbitrary message and verifying that. I haven't seen a way to do something like this via WaxJS. 

Could someone point me in the write direction? It would be preferable to be able to do this without pushing a transaction on chain.

Any help much appreciated :)

**Comment by kinsen** [comment]
hi @ismyhc , did you find a solution?

**Comment by ismyhc** [comment]
> hi @ismyhc , did you find a solution?

Unfortunately on solution found...

**Comment by niksad8** [comment]
we dont have this right now but we are planning to implement something like this soon

**Comment by niksad8** [comment]
there are two new functions in waxjs added for account verification one, is wax.waxProof(nonce) and the other is wax.userAccountProof(nonce)
