### ISSUE TITLE
trying to use eosio.msig with wax wallet

### ISSUE THREAD

**Issue by Starcadiaio** [worldwide-asset-exchange/waxjs#106]
Hello,

i've been trying to use actions from the contract eosio.msig, it works with anchor, but wax wallet sends the error "Error : Request failed with status code 403, This transaction contains forbidden actions".

It tried also what has been mentionned in this issue 

https://github.com/worldwide-asset-exchange/waxjs/issues/99

to set 'freeBandwidth' to false in the intialization but doesn't seem to allow WCW to sign a transaction that require authorization from multiple accounts.

Is the error 'This transaction contains forbidden actions' normal using eosio.msig ?
`
{"actions":
  [
   {"account":"eosio.msig",
    "name":"propose",
    "authorization":[
       {"actor":"3bhmm.c.wam","permission":"active"}
     ],
     "data":
      {
         "proposer":"3bhmm.c.wam",
         "proposal_name":"wjnnomfwv2zw",
         "requested":[
            {"actor":"3bhmm.c.wam","permission":"active"},
            {"actor":"hobby1testsc","permission":"active"}
          ],
         "trx":
           {
            "expiration":"2022-05-15T10:08:58", 
            "ref_block_num":0, 
            "ref_block_prefix":0, 
            "max_net_usage_words":0, 
            "max_cpu_usage_ms":0, 
            "delay_sec":0, 
            "context_free_actions":[], 
            "actions":[
               {
                     "account":"starcadiagam",
                     "name":"usemulti",
                      "authorization":[
                            {"actor":"3bhmm.c.wam","permission":"active"}, 
                           {"actor":"hobby1testsc","permission":"active"}
                      ], 
                      "data":"02FED86C0E0001000000A4E1000129DB19FBD86C0E000100008070C62A077F0E6DB3000000"
               }
           ], 
           "transaction_extensions":[]
        }
      }
     }
   ]}`
   
   
   same error if i create the proposal with anchor and try to execute the approve action with WCW.

**Comment by includenull** [comment]
multisig is blocked by WAX Cloud Wallet due to the fact it can be used to edit permissions and other actions that can break the way the custodial wallet works.

I don't see WAX Cloud Wallet allowing msig any time soon I'm afraid.
