### ISSUE TITLE
Documentation link gives a 404

### ISSUE THREAD

**Issue by NKCSS** [worldwide-asset-exchange/waxjs#128]
https://developer.wax.io/docs/wax-cloud-wallet/waxjs/
![image](https://user-images.githubusercontent.com/2622092/218436172-2312f253-343e-4324-9257-dfe8d1aa140f.png)

**Comment by niksad8** [comment]
please use this link for now will be updating it soon 
https://developer.wax.io/en/wax-cloud-wallet/waxjs/
