### ISSUE TITLE
ForbiddenTransactionException - Malicious website blocked

### ISSUE THREAD

**Issue by primersion** [worldwide-asset-exchange/waxjs#138]
Since a few days I am getting a ForbiddenTransactionException when trying to broadcast a transaction using wax cloud wallet:
`{error: "ForbiddenTransactionException", message: "Malicious website blocked"}`

I can't find any documentation on the issue - how to unblock my site or do I need to send some kind of api key / token for the transaction broadcast to go through? Updating to version 1.3.0 doesn't help either..

**Comment by niksad8** [comment]
@porkchop here is someone reporting this issue
@primersion can you please provide your website URL.

**Comment by primersion** [comment]
Thank you. The URL is https://waxcpu.me. It's a small service for renting CPU.

**Comment by porkchop** [comment]
@primersion please check I think this should be fixed now

**Comment by niksad8** [comment]
@primersion it should be fixed now please check

**Comment by primersion** [comment]
Yes it's working again. Thanks a lot!
