### ISSUE TITLE
Unstake Ram

### ISSUE THREAD

**Issue by YoungJuan** [worldwide-asset-exchange/waxjs#157]
My old version of Wax Bloks is apparently too old, and I was sent in this direction to update app in order to unstake

**Comment by Yingying886** [comment]
怎么更新怎么升级？

**Comment by niksad8** [comment]
@YoungJuan ask on discord in the #get-help channel you will find someone who will direct you properly

**Comment by wxm168168** [comment]
18059235220 微信交流一下你怎么处理没有办法链接钱包赎回质押的

**Comment by callmenemo491** [comment]
> My old version of Wax Bloks is apparently too old, and I was sent in this direction to update app in order to unstake

use:  https://waxblock.io/wallet/ram/sell  instead of wax.bloks.io...
