### ISSUE TITLE
Delete This Thread..

### ISSUE THREAD

**Issue by MathiewBurkett** [worldwide-asset-exchange/waxjs#160]
Splinterlands Issue with Atomichub.io
https://splinterlands.com/

Hi,

I thought that I would let someone know that there is an issue going on with transferring NFT's from Atomichub.io to Splinterlands.

When I purchase Splinterland NFT's at Atomichub.io, I am not able to transfer the NFT's to a Splinterlands Account because of the issue.

Here is the Error Message that I am receiving below,

"This application is currently utilizing an outdated version of waxjs that is no longer supported.

We kindly request you to contact the application's team to upgrade to the latest waxjs version by following this link.
https://github.com/worldwide-asset-exchange/waxjs"

Thanks,

Mathiew Burkett

**Comment by callmenemo491** [comment]
you have to contact Splinterlands.. for them to update the waxjs library to support the mycloudwallet.

**Comment by MathiewBurkett** [comment]
ok Theanks..
