### ISSUE TITLE
Sending WAX to activate a temporary account only creates the account on chain but does not set permissions.

### ISSUE THREAD

**Issue by rahul-webd** [worldwide-asset-exchange/waxjs#161]
I tried creating an account on behalf of a user. The flow is - The user logs in and gets a temporary account and then on the app he can request for his account to get activated. The problem occurs when a backend service has sent the 5 WAX for the wallet to be activated. The account gets created but the permissions are not set. I have tried doing this many times, but the same happens.

**Comment by callmenemo491** [comment]
Join the wax discord, and ask in the get-help channel.

**Comment by rahul-webd** [comment]
I simply followed up the instructions on the readme for how to set up the system. So, I believe this is the right place to ask.

https://github.com/worldwide-asset-exchange/waxjs#create-blockchain-account-on-behalf-of-the-user

**Comment by niksad8** [comment]
hi there the problem with the permissions is that the user needs to login atleast once for the permissions to be activated for the user. When the person transfers 5 wax to activate the account, the account is created but not permissioned till they atleast login once with the wallet.

**Comment by rahul-webd** [comment]
Sorry for the late reply. I tested the way you said, logging in at least once after transferring the WAX, but the permissions are still not set and this happens every time an account is created. Is there some service, which is triggered after the WAX is sent?

**Comment by niksad8** [comment]
when the person logs in to WCW the wallet is responsible for making sure the managed account is setup properly. That is why you need to login atleast once, if you are getting problems with wallets not being setup properly please provide a few wallet names and i can check them out

**Comment by rahul-webd** [comment]
This is not just a problem with a few wallets as I said earlier. Is there a working example somewhere of how to 'create accounts on someone else' behalf', It might be better to just go through the example than back and fro here. If not an open-source example then maybe a link to a project which is using this approach can be helpful too.

**Comment by niksad8** [comment]
i just did this twice with two different accounts and both activated when they logged in. 
when it comes to creating accounts 
- one is this system where you signup for account then transfer the amount and then login to the account to activate the signatures.
- there is another system of using activation codes with which lets you automate the whole process. 

the transfer of 5 wax was meant for users who want to create there account on behalf of others. then the new user logs in and everything is setup for them. 
there is also a system where using the backend people can activate the account using activation codes. You can buy activation codes from the support team. the cost the same really.
using codes the account gets setup and the permissions get setup also. 

I have seen fully integrated work flow but they use the following work flow : 
- say like sign up to website to make purchase, They can first just create the wallet. 
- second transfer the 5 waxp to newuser.wax with the correct memo. 
- at this point you can start interacting with the new wallet. But the user cant sign transactions. To sign the transactions the account needs to be activated by relogging, i think even if the person is on the dashboard is enough i feel. 

give this a try, make sure the user is relogging properly, even reloading is enough for temp accounts.

**Comment by rahul-webd** [comment]
When you tried creating accounts, did you keep the popup opened or closed? It works if the popup is open, but not if the popup is closed which happens in my case i.e. user gets a temporary account and the popup is closed. I believe when the popup is open it is actually triggering a service in the backend which sets the permissions. So, when the WAX is sent in my case, It does not trigger that service and hence the permissions are not set.

Try using this site - https://reptilium.io and creating an account with WCW. It will return a temporary account, then send 5 WAX to newuser.wax for that account. The permissions will not be set.

**Comment by niksad8** [comment]
this is what i did : 
- signed up for account 
- clicked on the email link account verified,
- i login to the account open the dialog copy the account name eg : lesoqDOTcDOTwam
- logout of this account
- open incognito window
- sign in with my main account 
- transfer 5 waxP to newuser.wax with memo lesoqDOTcDOTwam
- log in with the temp account above again the permissions are setup properly.

**Comment by rahul-webd** [comment]
Did you wait on the paywall screen at all?

**Comment by rahul-webd** [comment]
It seems that using the activation codes is the best way here. And with that, I am closing this issue.
