### ISSUE TITLE
Error with the module

### ISSUE THREAD

**Issue by lumoverix** [worldwide-asset-exchange/waxjs#168]
Not sure what to do here...

![image](https://github.com/worldwide-asset-exchange/waxjs/assets/148163478/b34eb6d4-4f14-484e-b89e-10cb3d4fb898)

**Comment by niksad8** [comment]
you have not initialized your waxjs/eosjs library properly. this is the jsonrpc code that should be inited properly. make sure the initing is done properly before calling this function that you are calling.

**Comment by lumoverix** [comment]
Thank you, when I provided data to the init it started to clear through.

` const wax = new waxjs.WaxJS({
            rpcEndpoint: 'https://wax.greymass.com',
            userAccount: 'abc123',
            pubKeys: ['PUB_K1_']
        });`
