### ISSUE TITLE
https://all-access.wax.io/cloud-wallet/login/ error

### ISSUE THREAD

**Issue by Pokeban** [worldwide-asset-exchange/waxjs#217]
Hi, can somebody pls help me.? Wenn I try to login on my wax cloud wallet, I got this message:

This application is currently utilizing an outdated version of waxjs that is no longer supported.
We kindly request you to contact
the application's team to upgrade to the latest waxjs version by following this link.

what should I do now?

**Comment by includenull** [comment]
You simply need to update to the latest version of waxjs in your project.
