### ISSUE TITLE
[Bug] signViaEndpoint Don't worked

### ISSUE THREAD

**Issue by WxSimon** [worldwide-asset-exchange/waxjs#43]
I use signViaEndpoint for auto sign.

But the http response is :

```
{"errors":[{"error_type":"Unauthorized","message":"Session token invalid or expired","error_code":"0"}]}
```

**Comment by L-WJ1995** [comment]
Did you solve it?

**Comment by includenull** [comment]
I believe this is the response from the auto signing endpoint when the dapp url is not whitelisted by the user.

How are you using signViaEndpoint? It should be left up to waxjs to decide if it should be used or not based on the list of whitelisted dapps that it gets from logging the user in.
