### ISSUE TITLE
Transferring NFTs

### ISSUE THREAD

**Issue by m6cheung** [worldwide-asset-exchange/waxjs#58]
Is it possible to transfer NFTs with this module or does it only work for transferring fungible tokens?

**Comment by CiFrameVladislavB** [comment]
The issue is closed, but it's really neccecary to know, how to transfer NFT.

**Comment by pratikbaid3** [comment]
@m6cheung did you find a way to transfer nft using the waxjs package?

**Comment by CiFrameVladislavB** [comment]
> @m6cheung did you find a way to transfer nft using the waxjs package?

I wrote the solution somewhere in eosjs repo.

**Comment by pratikbaid3** [comment]
@CiFrameVladislavB any chance you can point me to it. A link will be helpful.

**Comment by SebZachrau** [comment]
I have the same problem right now too and an example would be very helpful

**Comment by kaefergeneral** [comment]
need to push an atomicassets transfer action with the IDs you want to send.
For reference:
https://wax.bloks.io/account/atomicassets?loadContract=true&tab=Actions&account=atomicassets&scope=atomicassets&limit=100&action=transfer
