### ISSUE TITLE
Not working in Electronjs

### ISSUE THREAD

**Issue by matheusqro** [worldwide-asset-exchange/waxjs#63]
Hi my friend, you are not working on Electronjs.

- I'm using ReactJS + ElectronJS and it's not working.
- Does not return anything from the promise, Nothing happens.
- In ReactJS it works, but using Electron JS the package doesn't work.

**Comment by includenull** [comment]
You will probably have to write your own package to work with Electron, one that can open an external browser window.

WaxJS by design will only work in a browser.
