### ISSUE TITLE
Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by vaibhavyadav12** [worldwide-asset-exchange/waxjs#71]
I am using 0.0.7 version of @waxio/waxjs in js.
I am trying to call the `wax.login()` it gives me error `Cannot read property 'replace' of undefined` 
I believe there's an error with the library -  wax.js .  I have tried running the sdk example as well as the full html example as represented in the docs.
[](https://developer.wax.io/waa/waxjs-demo/) 

Can anyone help me out on this error ? 
Thanks

**Comment by brett91ag** [comment]
I get the same error using the example code with the current version.  I don't get the error when I use v0.0.15

**Comment by robrigo** [comment]
Double check how you initialize the waxjs object. I had to add the rpcEndpoint key.

```
const wax = new waxjs.WaxJS({ rpcEndpoint: GLOBAL_VARS.WAX_RPC_ENDPOINT });
```

**Comment by includenull** [comment]
The constructor changed with with version 1.0, wax developer hive is still outdated unfortunately.
