### ISSUE TITLE
Signing Issue

### ISSUE THREAD

**Issue by abdulmanan7** [worldwide-asset-exchange/waxjs#72]
Sometimes it works sometimes throw the following message.
transaction declares authority '{"actor":"myaccountname","permission":"active"}', but does not have signatures for it under a provided delay of 0 ms, provided permissions [], provided keys [], and a delay max limit of 3888000000 ms

I check waxjs in console the object is fine, i enable autologin and do check before transaction but failed 

```
    let isAutoLoginAvailable = await wax.isAutoLoginAvailable();
    if (!isAutoLoginAvailable) {
        await wax.login();
    }
    let userAccount = wax.userAccount;
    try {
        let result = await wax.api.transact({
            actions: [{
                account: 'atomicassets',
                name: 'transfer',
                authorization: [{
                    actor: userAccount,
                    permission: 'active',
                }],
                data: data,
            }]
        }, {
            blocksBehind: 12,
            expireSeconds: 120,
            broadcast: true,
            sign: true,
        }).then((d) => console.log(d)).catch(onErrorCallback)
        return result;
    } catch (error) {
        return onErrorCallback(error)
    }
```

**Comment by eloventure** [comment]
Here is what helped me a lot:
`expireSeconds: 120` -> `change to expireSeconds: 10`
and
`blocksBehind: 12` -> `blocksBehind: 1`

**Comment by Farfar10** [comment]
but does not have signatures for it under a provided delay of 0 ms, provided permissions [], provided keys [], and a delay max limit of 3888000000 ms

**Comment by Farfar10** [comment]
this?
https://github.com/worldwide-asset-exchange/waxjs/pull/64

**Comment by includenull** [comment]
> this? #64

Yes, we hope to have this RP tested and implemented soon.

**Comment by includenull** [comment]
waxjs 1.0.4 should resolve these issues.
