### ISSUE TITLE
How to use it on raw NodeJS

### ISSUE THREAD

**Issue by KaffinPX** [worldwide-asset-exchange/waxjs#75]
fetch doesnt supported defaultly, we can just use node-fetch but wax cloud wallet auth thing making it really centralised and i cant open auth page from raw nodejs.

**Comment by includenull** [comment]
waxjs is a frontend library, what are you trying to achieve with this in nodejs?

**Comment by KaffinPX** [comment]
> waxjs is a frontend library, what are you trying to achieve with this in nodejs?

Creating a tipbot for Discord. But i cant login with wax cloud wallet when no gui.

**Comment by includenull** [comment]
> Creating a tipbot for Discord. But i cant login with wax cloud wallet when no gui.

Are you trying to use waxjs for your bot, or for user to interact with the bot?

If you're trying to use it for your bot then this really isn't possible, you would need to create a custom named account and control it with eosjs or cleos.

If you need it for users to interact with your bot then you will probably need some sort of frontend for users to link their Discord and WAX account?

waxjs will only work for frontend uses.

**Comment by Dave-Melia** [comment]
Does anyone know of any tool that allows login from the terminal rather than the browser?

I'm trying to write a command line script for arbitrage and can't figure out how to login from the terminal.

**Comment by includenull** [comment]
> Does anyone know of any tool that allows login from the terminal rather than the browser?

This is not possible for WAX Cloud Wallet accounts, you would need to use eosjs or cleos with a account where you control your own key pairs.

**Comment by Dave-Melia** [comment]
I should have checked here sooner, I've just figured that out lol.  Thanks <3
