### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by vaibhavyadav12** [worldwide-asset-exchange/waxjs#77]
Hi, I have an issue when i use the wax sample code of wax ref- https://developer.wax.io/waa/waxjs-demo/   
i click the sendToken button for  send transaction function to transfer WAX, I got an error (Cannot read property 'length' of undefined) before the window popup . 

I m using this function to send the transfer function
Code-->
async function sendToken() {
            if (!wax.api) {
                return document.getElementById('response').append('* Login first *');
            }
            try {
                const result = await wax.api.transact({
                    actions: [{
                        account: 'eosio.token',
                        name: 'transfer',
                        authorization: [{
                            actor: wax.userAccount,
                            permission: 'active',
                        }],
                        data: {
                            from: wax.userAccount,
                            to: 'jahvu.wam',
                            quantity: '0.1 WAX',
                            memo: 'demo ',
                        },
                    }]
                }, {
                    blocksBehind: 3,
                    expireSeconds: 1200,
                });
                // console.log("result===>", result);
                document.getElementById('response').append(JSON.stringify(result, null, 2))
            } catch (e) {
                // console.log("hello", e);
                document.getElementById('response').append(e.message);
            }
        }
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
If anyone know about how to solve this error..!!

![Screenshot from 2021-08-30 19-27-02](https://user-images.githubusercontent.com/84623508/131350809-6d955f2a-708b-47b0-b3c4-caf724d30ec9.png)

**Comment by GuiiDo** [comment]
Hi, seems like you are missing the amount precision. For wax this is 8. Meaning that you have to provide 8 decimals. So your amount you would like to transfer would need to be 0.10000000. Hope this helps you out!

**Comment by vaibhavyadav12** [comment]
> Hi, seems like you are missing the amount precision. For wax this is 8. Meaning that you have to provide 8 decimals. So your amount you would like to transfer would need to be 0.10000000. Hope this helps you out!

Thank u for your response
It showing the same error

**Comment by includenull** [comment]
We are aware of this error and are tracking it, there is a pull request in that we think will resolve this but it is ultimately caused by the WAX Cloud Wallet signing window firing events twice. It seems to effect some users more than others, not sure if its a latency issue or something.

But yes, we're looking to get this resolved soon, the same issue has presented itself as many different error messages in the last year but its been the same cause.

**Comment by nhhoang** [comment]
Hi @includenull, did you fix this issue, I'm getting this issue too

**Comment by racquemis** [comment]
Any updates regarding this issue?

**Comment by abdulmanan7** [comment]
Any update on this error , i am also facing same error
