### ISSUE TITLE
cloud wallet redirecting doesn't work on webkit of LINE app

### ISSUE THREAD

**Issue by tamngaan** [worldwide-asset-exchange/waxjs#80]
![Screenshot (Oct 3, 2021 13_00_21)](https://user-images.githubusercontent.com/92017734/136163734-c65e7b72-2a7d-408f-b21e-bb348da8289d.png)

hello I tried to create new wallet from webkit of LINE app but counting-down and redirecting doesn't work.
is it available to put a link "click/tap here if redirecting doesn't work in 5 seconds" on this page?

also it would be great if you have multi-language on this page, thanks!

**Comment by includenull** [comment]
I have passed this on to the relevant team.
