### ISSUE TITLE
Link to documentation gives 404

### ISSUE THREAD

**Issue by NKCSS** [worldwide-asset-exchange/waxjs#93]
Readme.md points to https://developer.wax.io/waa/waxjs-overview/ which gives a 404 this should now be https://developer.wax.io/docs/wax-cloud-wallet/waxjs/

**Comment by NKCSS** [comment]
Submitted a pull request to fix it: https://github.com/worldwide-asset-exchange/waxjs/pull/94

**Comment by niksad8** [comment]
merged
