### ISSUE TITLE
How to find the profile endpoint with the identity_wcw scope

### ISSUE THREAD

**Issue by slilp** [worldwide-asset-exchange/waxjs#95]
I see that we can pass the account name and public keys to instantiate the object but I don't know how to find them from this sentence.

If you use the WAX Cloud Wallet OA service to sign a user in, you can use the profile endpoint with the identity_wcw scope to get a user’s WAX Blockchain Account name and public keys.

**Comment by includenull** [comment]
This is a remnant of the deprecated WAX OAuth and is no longer available.

The developer docs will be updated to fix that section soon.
